[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# required for running OpenZeppelin Upgrades CLI for upgrade safety checks
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
