name: slither

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: ["*"]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  check:
    timeout-minutes: 10
    strategy:
      fail-fast: true

    name: slither
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          solc-version: "0.8.21"
