name: snapshot

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: ["*"]
    paths-ignore:
      - README.md
      - .gitignore

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    timeout-minutes: 30
    strategy:
      fail-fast: true

    name: forge snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge snapshot
        run: |
          forge snapshot --check
        id: snapshot
        env:
          # make fuzzing deterministic to keep snapshots consistent
          FOUNDRY_FUZZ_SEED: 42
