name: test-via-ir

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: ["*"]
    paths-ignore:
      - README.md
      - .gitignore

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    timeout-minutes: 30
    strategy:
      fail-fast: true

    name: forge test via IR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests (via IR)
        run: |
          forge test -vvv --via-ir
        id: test
